export { coachrouter } from "./CommunityRoutes/Coach.js";
export {commentatorrouter} from "./CommunityRoutes/Commentator.js";
export {groundrouter} from "./CommunityRoutes/Ground.js";
export {scorerrouter} from "./CommunityRoutes/Scorer.js";
export {shoprouter} from "./CommunityRoutes/Shop.js";
export {streamerrouter} from "./CommunityRoutes/Streamer.js";
export {tshirtrouter} from "./CommunityRoutes/TShirt.js";
export {umpirerouter} from "./CommunityRoutes/Umpire.js";
export {groundlookingrouter} from "./LookingRoutes/GroundLooking.js";
export {opponentrouter} from "./LookingRoutes/Opponent.js";
export {playerforteamrouter} from "./LookingRoutes/PlayerForTeam.js";
export {scorerlookingrouter} from "./LookingRoutes/ScorerLooking.js";
export {teamforplayerrouter} from "./LookingRoutes/TeamForPlayer.js";
export {teamsfortournamentrouter} from "./LookingRoutes/TeamsForTournament.js";
export {tournamenttoparticipaterouter} from "./LookingRoutes/TournamentToParticipate.js";
export {umpirelookingrouter} from "./LookingRoutes/UmpireLooking.js";
export {userrouter} from "./MyCricketRoutes/User.js";
export {loginrouter} from "./MyCricketRoutes/Login.js";
export {signuprouter} from "./MyCricketRoutes/Signup.js";

