POST http://localhost:4000/api/coachform/
Content-Type: application/json

{
     "name":"harsh",
    "city":"gzb",
    "feesPM":"1000",
    "feesPD":"1000",
    "contact":"9219312312",
    "photo":""
}